version: '2'
services:
  rq-dashboard:
    image: eoranged/rq-dashboard
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redistest:6379/2
    links:
    - redistest:redistest
    ports:
      - "9181:9181"
  test:
    image: docker-registry.crt.nersc.gov:5000/alpine/omni-modbus-worker:2.0.4
    entrypoint:
    - sleep
    command:
    - '86400'
    labels:
      io.rancher.scheduler.affinity:host_label: net.modbus=true,net.trendpoint=true
      io.rancher.container.pull_image: always
  trendpoint:
    image: docker-registry.crt.nersc.gov:5000/alpine/omni-modbus-worker:2.0.4
    entrypoint:
    - python
    links:
    - master:master
    - redistest:redistest
    command:
    - ./omni-modbus-poller/scripts/modbus_rq_worker.py
    - -q
    - trendpoint
    - --redis=redistest
    labels:
      io.rancher.scheduler.affinity:host_label: net.modbus=true,net.trendpoint=true
      io.rancher.container.pull_image: always
  omni-cfg-redis-dbs:
    image: docker-registry.crt.nersc.gov:5000/alpine/omni-modbus-worker:2.0.4
    entrypoint:
    - python
    command:
    - ./omni-modbus-poller/scripts/redis-dbs.py
    - config
    - --redis=redistest
    labels:
      io.rancher.scheduler.affinity:host_label: net.modbus=true,net.trendpoint=true
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
  omni-cfg-redis-meter:
    image: docker-registry.crt.nersc.gov:5000/alpine/omni-modbus-worker:2.0.4
    entrypoint:
    - python
    command:
    - ./omni-modbus-poller/scripts/redis-dbs.py
    - meter
    - ${modbus_gateway}
    - --redis=redistest
    labels:
      io.rancher.scheduler.affinity:host_label: net.modbus=true,net.trendpoint=true
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
  redistest:
    image: redis:alpine
    environment:
      RANCHER_SERVICE_NAME: redistest
    ports:
    - 6379:6379/tcp
    labels:
      io.rancher.container.dns: 'true'
      io.rancher.service.wait_for_healthcheck: 'true'
      io.rancher.sidekicks: omni-cfg-redis-dbs,omni-cfg-redis-meter,omni-cfg-redis-points
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.network: 'true'
      io.rancher.scheduler.affinity:host_label: net.modbus=true,net.trendpoint=true
      io.rancher.container.hostname_override: container_name
  omni-cfg-redis-points:
    image: docker-registry.crt.nersc.gov:5000/alpine/omni-modbus-worker:2.0.4
    entrypoint:
    - python
    command:
    - ./omni-modbus-poller/scripts/redis-dbs.py
    - points
    - --redis=redistest
    labels:
      io.rancher.scheduler.affinity:host_label: net.modbus=true,net.trendpoint=true
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
  master:
    image: docker-registry.crt.nersc.gov:5000/alpine/omni-modbus-worker:2.0.4
    entrypoint:
    - python
    links:
    - redistest:redistest
    command:
    - ./omni-modbus-poller/scripts/modbus_rq_master.py
    - --redis=redistest
    - --rabbit=rabbit-internal.crt.nersc.gov
    - --sleep=10
    - --iterations=50
    labels:
      io.rancher.container.pull_image: always
