version: '2'
services:
  cowcheck:
    image: wjimenez5271/cowcheck:0.2.0
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      ENABLE_STORAGE_CHECK: ${ENABLE_STORAGE_CHECK}
      DOCKER_API_VERSION: ${DOCKER_API_VERSION}
      DATA_SPACE_THRESHOLD: ${DATA_SPACE_THRESHOLD}
      METADATA_SPACE_THRESHOLD: ${METADATA_SPACE_THRESHOLD}
      POLL_INTERVAL: ${POLL_INTERVAL}
    stdin_open: true
    tty: true
    ports:
    - ${PUBLISH_PORT}:5050/tcp
    labels:
      io.rancher.scheduler.global: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
