name: NERSC Sensor REST API
description: |
    REST API for interacting with NERSC Sensor infrastructure
version: 1.0.0
category:  Sensors
maintainer: Joshua Boverhof
license: # The license
projectURL: # A URL related to the catalog entry
