name: ION Meter HTTP scrapper
description: |
  Uses the ION meter HTTP interface to get values.
version: 0.1
category: ion
maintainer: "Thomas Davis <tadavis@lbl.gov>"
minimum_rancher_version: v1.0.0
license: 
