name: ION Meter HTTP/HTML scraper
description: |
  Uses the ION meter HTTP interface to get values.
version: 3
category: ion
maintainer: "Thomas Davis <tadavis@lbl.gov>"
minimum_rancher_version: v1.0.0
license: 
