pdu:
  image: docker-registry.crt.nersc.gov:5000/mini/modbus-worker:0.2
  command: -q modbus2
  labels:
    io.rancher.scheduler.affinity:host_label: net.modbus=true
ion:
  image: docker-registry.crt.nersc.gov:5000/mini/modbus-worker:0.2
  command: -q ion2
  labels:
    io.rancher.scheduler.affinity:host_label: net.substation=true
ups:
  image: docker-registry.crt.nersc.gov:5000/mini/modbus-worker:0.2
  command: -q ups2
  labels:
    io.rancher.scheduler.affinity:host_label: net.ups=true
master:
  image: docker-registry.crt.nersc.gov:5000/mini/modbus-worker:0.2
  container_name: modbus_master
  entrypoint: python
  command: "./pulsar/scripts/pulsar_job_producer.py --suffix=2"
