name: Airborne Particle Counter
description: |
    Application for polling Lighthouse 3014P Airborne Particle Counters
version: 0.5
category:  Sensors
maintainer: Joshua Boverhof
license: # The license
projectURL: # A URL related to the catalog entry
