pue-master:
  image: docker-registry.crt.nersc.gov:5000/alpine/pue-data-reduction:0.1
  command: "/opt/nersc/scripts/master.sh"

pue-slave:
  image: docker-registry.crt.nersc.gov:5000/alpine/pue-data-reduction:0.1
  command: "/opt/nersc/scripts/worker.py"
