bacnet:
  image: docker-registry.crt.nersc.gov:5000/alpine/ion-web-scrape:0.2
  command: "/opt/ionscraper/ion-scraper.sh"
  net: host
  labels:
      io.rancher.scheduler.affinity:host_label: net.substations=true

