pdu:
  image: docker-registry.crt.nersc.gov:5000/mini/modbus-worker:0.4
  command: -q modbus4
  labels:
    io.rancher.scheduler.affinity:host_label: net.modbus=true
ion:
  image: docker-registry.crt.nersc.gov:5000/mini/modbus-worker:0.4
  command: -q ion4
  labels:
    io.rancher.scheduler.affinity:host_label: net.substation=true
ups:
  image: docker-registry.crt.nersc.gov:5000/mini/modbus-worker:0.4
  command: -q ups4
  labels:
    io.rancher.scheduler.affinity:host_label: net.ups=true
master:
  image: docker-registry.crt.nersc.gov:5000/mini/modbus-worker:0.4
  container_name: modbus_master
  entrypoint: python
  command: "./pulsar/scripts/pulsar_job_producer.py --suffix=4"
