motioneye:
  container_name: motioneye
  image: docker-registry.crt.nersc.gov:5000/f23/motioneye:0.31.3
  ports:
    - 8765
  labels:
    io.rancher.container.hostname_override: ${stack_name}
  volumes:
    - /etc/motioneye
    - /var/lib/motioneye
