name: Trendpoint
description: |
    Application for Trendpoint Enkapsis and BCPM meters on Perlmutter System
version: 0.5
category:  Sensors
maintainer: Joshua Boverhof
license: # The license
projectURL: # A URL related to the catalog entry
